openapi: 3.0.0
info:
  description: |
    Mock API
  version: 1.0.0
  title: Mock API
tags:
  - name: login
    description: Login API
  - name: user
    description: User API
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
paths:
  /login:
    post:
      tags:
        - login
      summary: Login
      description: ""
      operationId: login
      requestBody:
        $ref: "#/components/requestBodies/LoginRequest"
      responses:
        "200":
          description: successful operation
          content:
            application/json::
              schema:
                $ref: "#/components/schemas/User"
  /login/user:
    get:
      tags:
        - login
      summary: Login
      description: ""
      operationId: getCurrentAuthenticatedUser
      responses:
        "200":
          description: successful operation
          content:
            application/json::
              schema:
                $ref: "#/components/schemas/User"
  /user:
    get:
      tags:
        - user
      summary: find users
      description: ""
      operationId: findUsers
      parameters:
        - name: itemsPerPage
          in: query
          required: false
          description: 取得件数
          schema:
            type: integer
            format: int32
        - name: pageNo
          in: query
          required: false
          description: ページ番号
          schema:
            type: integer
            format: int32
        - name: userId
          in: query
          description: ""
          required: false
          schema:
            type: string
        - name: lastName
          in: query
          description: ""
          required: false
          schema:
            type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json::
              schema:
                $ref: "#/components/schemas/UserResult"
    post:
      tags:
        - user
      summary: Create User
      description: ""
      operationId: createUser
      requestBody:
        $ref: "#/components/requestBodies/User"
      responses:
        "200":
          description: OK
    put:
      tags:
        - user
      summary: Edit User
      description: ""
      operationId: editUser
      requestBody:
        $ref: "#/components/requestBodies/User"
      responses:
        "200":
          description: OK
  /user/{id}:
    get:
      tags:
        - user
      summary: find user
      description: ""
      operationId: getUser
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
          description: ""
      responses:
        "200":
          description: successful operation
          content:
            application/json::
              schema:
                $ref: "#/components/schemas/User"
    delete:
      tags:
        - user
      summary: Remove User
      description: ""
      operationId: removeUser
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
          description: ""
      responses:
        "200":
          description: OK
components:
  requestBodies:
    LoginRequest:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Login"
      description: List of user object
      required: true
    User:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/User"
      description: List of user object
      required: true
  schemas:
    Login:
      type: object
      properties:
        userId:
          type: string
        password:
          type: string
          format: password
    UserResult:
      type: object
      properties:
        totalItems:
          type: integer
          format: int32
        users:
          type: array
          items:
            $ref: "#/components/schemas/User"
    User:
      type: object
      properties:
        id:
          type: integer
          format: int32
          readOnly: true
        userId:
          type: string
          minLength: 4
          maxLength: 32
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        birthday:
          type: string
          format: date
      required:
        - userId
        - firstName
        - lastName
