/**
 * Mock API
 * Mock API
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface UserDTO {
  id?: number
  userId?: string
  firstName?: string
  lastName?: string
  email?: string
  password?: string
}
