/**
 * Mock API
 * Mock API
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core'
import {
  HttpClient,
  HttpHeaders,
  HttpParams,
  HttpResponse,
  HttpEvent
} from '@angular/common/http'
import { CustomHttpUrlEncodingCodec } from '../encoder'

import { Observable } from 'rxjs'

import { UserDTO } from '../model/user-dto'
import { UsersDTO } from '../model/users-dto'

import { BASE_PATH, COLLECTION_FORMATS } from '../variables'
import { Configuration } from '../configuration'

@Injectable({
  providedIn: 'root'
})
export class UserApi {
  protected basePath = 'http://localhost'
  public defaultHeaders = new HttpHeaders()
  public configuration = new Configuration()

  constructor(
    protected httpClient: HttpClient,
    @Optional() @Inject(BASE_PATH) basePath: string,
    @Optional() configuration: Configuration
  ) {
    if (configuration) {
      this.configuration = configuration
      this.configuration.basePath =
        configuration.basePath || basePath || this.basePath
    } else {
      this.configuration.basePath = basePath || this.basePath
    }
  }

  /**
   * @param consumes string[] mime-types
   * @return true: consumes contains 'multipart/form-data', false: otherwise
   */
  private canConsumeForm(consumes: string[]): boolean {
    const form = 'multipart/form-data'
    for (const consume of consumes) {
      if (form === consume) {
        return true
      }
    }
    return false
  }

  /**
   * Create User
   *
   * @param userDTO List of user object
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public createUser(
    userDTO: UserDTO,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<any>
  public createUser(
    userDTO: UserDTO,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<any>>
  public createUser(
    userDTO: UserDTO,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<any>>
  public createUser(
    userDTO: UserDTO,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    if (userDTO === null || userDTO === undefined) {
      throw new Error(
        'Required parameter userDTO was null or undefined when calling createUser.'
      )
    }

    let headers = this.defaultHeaders

    // to determine the Accept header
    const httpHeaderAccepts: string[] = []
    const httpHeaderAcceptSelected:
      | string
      | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts)
    if (httpHeaderAcceptSelected !== undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected)
    }

    // to determine the Content-Type header
    const consumes: string[] = ['application/json']
    const httpContentTypeSelected:
      | string
      | undefined = this.configuration.selectHeaderContentType(consumes)
    if (httpContentTypeSelected !== undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected)
    }

    return this.httpClient.post<any>(
      `${this.configuration.basePath}/user`,
      userDTO,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    )
  }

  /**
   * Edit User
   *
   * @param userDTO List of user object
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public editUser(
    userDTO: UserDTO,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<any>
  public editUser(
    userDTO: UserDTO,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<any>>
  public editUser(
    userDTO: UserDTO,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<any>>
  public editUser(
    userDTO: UserDTO,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    if (userDTO === null || userDTO === undefined) {
      throw new Error(
        'Required parameter userDTO was null or undefined when calling editUser.'
      )
    }

    let headers = this.defaultHeaders

    // to determine the Accept header
    const httpHeaderAccepts: string[] = []
    const httpHeaderAcceptSelected:
      | string
      | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts)
    if (httpHeaderAcceptSelected !== undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected)
    }

    // to determine the Content-Type header
    const consumes: string[] = ['application/json']
    const httpContentTypeSelected:
      | string
      | undefined = this.configuration.selectHeaderContentType(consumes)
    if (httpContentTypeSelected !== undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected)
    }

    return this.httpClient.put<any>(
      `${this.configuration.basePath}/user`,
      userDTO,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    )
  }

  /**
   * find users
   *
   * @param from
   * @param to
   * @param userId
   * @param lastName
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public findUsers(
    from: number,
    to: number,
    userId?: string,
    lastName?: string,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<UsersDTO>
  public findUsers(
    from: number,
    to: number,
    userId?: string,
    lastName?: string,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<UsersDTO>>
  public findUsers(
    from: number,
    to: number,
    userId?: string,
    lastName?: string,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<UsersDTO>>
  public findUsers(
    from: number,
    to: number,
    userId?: string,
    lastName?: string,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    if (from === null || from === undefined) {
      throw new Error(
        'Required parameter from was null or undefined when calling findUsers.'
      )
    }
    if (to === null || to === undefined) {
      throw new Error(
        'Required parameter to was null or undefined when calling findUsers.'
      )
    }

    let queryParameters = new HttpParams({
      encoder: new CustomHttpUrlEncodingCodec()
    })
    if (userId !== undefined && userId !== null) {
      queryParameters = queryParameters.set('userId', <any>userId)
    }
    if (lastName !== undefined && lastName !== null) {
      queryParameters = queryParameters.set('lastName', <any>lastName)
    }

    let headers = this.defaultHeaders

    // to determine the Accept header
    const httpHeaderAccepts: string[] = ['application/json:']
    const httpHeaderAcceptSelected:
      | string
      | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts)
    if (httpHeaderAcceptSelected !== undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected)
    }

    // to determine the Content-Type header
    const consumes: string[] = []

    return this.httpClient.get<UsersDTO>(
      `${this.configuration.basePath}/user/${encodeURIComponent(
        String(from)
      )}/${encodeURIComponent(String(to))}`,
      {
        params: queryParameters,
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    )
  }

  /**
   * Remove User
   *
   * @param id
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public removeUser(
    id: number,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<any>
  public removeUser(
    id: number,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<any>>
  public removeUser(
    id: number,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<any>>
  public removeUser(
    id: number,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    if (id === null || id === undefined) {
      throw new Error(
        'Required parameter id was null or undefined when calling removeUser.'
      )
    }

    let headers = this.defaultHeaders

    // to determine the Accept header
    const httpHeaderAccepts: string[] = []
    const httpHeaderAcceptSelected:
      | string
      | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts)
    if (httpHeaderAcceptSelected !== undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected)
    }

    // to determine the Content-Type header
    const consumes: string[] = []

    return this.httpClient.delete<any>(
      `${this.configuration.basePath}/user/${encodeURIComponent(String(id))}`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    )
  }
}
