/**
 * Mock API
 * Mock API
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core'
import {
  HttpClient,
  HttpHeaders,
  HttpParams,
  HttpResponse,
  HttpEvent
} from '@angular/common/http'
import { CustomHttpUrlEncodingCodec } from '../encoder'

import { Observable } from 'rxjs'

import { UserResponseDTO } from '../model/user-response-dto'

import { BASE_PATH, COLLECTION_FORMATS } from '../variables'
import { Configuration } from '../configuration'

@Injectable({
  providedIn: 'root'
})
export class UserApi {
  protected basePath = 'https://petstore.swagger.io/v2'
  public defaultHeaders = new HttpHeaders()
  public configuration = new Configuration()

  constructor(
    protected httpClient: HttpClient,
    @Optional() @Inject(BASE_PATH) basePath: string,
    @Optional() configuration: Configuration
  ) {
    if (configuration) {
      this.configuration = configuration
      this.configuration.basePath =
        configuration.basePath || basePath || this.basePath
    } else {
      this.configuration.basePath = basePath || this.basePath
    }
  }

  /**
   * @param consumes string[] mime-types
   * @return true: consumes contains 'multipart/form-data', false: otherwise
   */
  private canConsumeForm(consumes: string[]): boolean {
    const form = 'multipart/form-data'
    for (const consume of consumes) {
      if (form === consume) {
        return true
      }
    }
    return false
  }

  /**
   * find users
   *
   * @param userId
   * @param lastName
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public finfUsers(
    userId?: string,
    lastName?: string,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<Array<UserResponseDTO>>
  public finfUsers(
    userId?: string,
    lastName?: string,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<Array<UserResponseDTO>>>
  public finfUsers(
    userId?: string,
    lastName?: string,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<Array<UserResponseDTO>>>
  public finfUsers(
    userId?: string,
    lastName?: string,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    let queryParameters = new HttpParams({
      encoder: new CustomHttpUrlEncodingCodec()
    })
    if (userId !== undefined && userId !== null) {
      queryParameters = queryParameters.set('userId', <any>userId)
    }
    if (lastName !== undefined && lastName !== null) {
      queryParameters = queryParameters.set('lastName', <any>lastName)
    }

    let headers = this.defaultHeaders

    // to determine the Accept header
    const httpHeaderAccepts: string[] = ['application/json:']
    const httpHeaderAcceptSelected:
      | string
      | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts)
    if (httpHeaderAcceptSelected !== undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected)
    }

    // to determine the Content-Type header
    const consumes: string[] = []

    return this.httpClient.get<Array<UserResponseDTO>>(
      `${this.configuration.basePath}/user`,
      {
        params: queryParameters,
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    )
  }
}
